name: phemed
channels:
- bioconda
dependencies:
- python=3.7.4
- bitarray=1.0.1
- pip
- pip:
  - scipy==1.3.1
  - pandas==0.25.1
  - numpy==1.17.2
  - matplotlib==3.1.1
  - argparse==1.1
  - seaborn==0.9.0
